apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: programs.mydomain.org
spec:
  group: mydomain.org
  names:
    kind: Program
    listKind: ProgramList
    plural: programs
    singular: program
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                version:
                  type: string
                description:
                  type: string
                image:
                  type: string
                options:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      type:
                        type: string
                      description:
                        type: string
                      default:
                        type: string
                commands:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      description:
                        type: string
                      parameters:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            type:
                              type: string
                            description:
                              type: string
                            optional:
                              type: boolean
                      returns:
                        type: string
                      cmd:
                        type: string
